//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.CSharpDemoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://github.com/victorbu/csharpdemo", ConfigurationName="CSharpDemoService.CSharpDemoService")]
    public interface CSharpDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/victorbu/csharpdemo/CSharpDemoService/Hello", ReplyAction="https://github.com/victorbu/csharpdemo/CSharpDemoService/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/victorbu/csharpdemo/CSharpDemoService/Hello", ReplyAction="https://github.com/victorbu/csharpdemo/CSharpDemoService/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CSharpDemoServiceChannel : WCF.Client.CSharpDemoService.CSharpDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSharpDemoServiceClient : System.ServiceModel.ClientBase<WCF.Client.CSharpDemoService.CSharpDemoService>, WCF.Client.CSharpDemoService.CSharpDemoService {
        
        public CSharpDemoServiceClient() {
        }
        
        public CSharpDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSharpDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSharpDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSharpDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync() {
            return base.Channel.HelloAsync();
        }
    }
}
