//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.GithubService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://github.com/victorbu", ConfigurationName="GithubService.GithubService")]
    public interface GithubService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/victorbu/GithubService/Hello", ReplyAction="https://github.com/victorbu/GithubService/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/victorbu/GithubService/Hello", ReplyAction="https://github.com/victorbu/GithubService/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GithubServiceChannel : WCF.Client.GithubService.GithubService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GithubServiceClient : System.ServiceModel.ClientBase<WCF.Client.GithubService.GithubService>, WCF.Client.GithubService.GithubService {
        
        public GithubServiceClient() {
        }
        
        public GithubServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GithubServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GithubServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GithubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync() {
            return base.Channel.HelloAsync();
        }
    }
}
